### ISSUE TITLE
How's it going?

### ISSUE THREAD

**Issue by cyrus01337** [cibere/discord-bot-made-with-no-communication#4]
Non-issue because I am very cool

**Comment by cibere** [comment]
Hey! we are currently waiting on `le ducki3#5564` to do their portion. But we 4 devs out of 8 done.

**Comment by cibere** [comment]
4/7*

**Comment by cyrus01337** [comment]
Sounds like you're all having fun, bet it's as messy as it sounds. Y'all planning on doing anything further with this?

**Comment by cibere** [comment]
Nothings been discussed regarding what will happen afterwards, though i do have plans to do this experiment again but with a little twist. Though a couple of the devs have put the code in their bots

**Comment by cyrus01337** [comment]
Funky, have fun!

**Comment by cibere** [comment]
Closing this due to
1) not an actual issue
2) inactive
